SHEET_URL = "https://docs.google.com/spreadsheets/d/1lFzORBHLPILhAGvNgK15ulbrIzYzimDnATcMWbEbCO0/edit?usp=sharing"

[SERVICE_ACCOUNT_INFO]
project_id = "voting-kds"
type = "service_account"
private_key_id = "99a6ff0cd760f60a6a96ce7ae88a9f6b722d8a15"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDFXGOoA8ptefZr
90DLL7uzj12GdrdKraaVsOTNbfK/L6ZgRocJpf//zu1LFDUm7/3N1kD86yxzB28L
yVdIJA0AXgjapXXNBWBclj93vBgiQSocAWMiFCrfEqV9OzG1hZKet5CD+33CSraX
gr0V305tybgrOp/OSC8serpEDMY/7dPEtz4Dtown5Zs7xNyCj/zKqt/Sp+6C3uXb
rnseja1g0nutY7+LnOW0YNL5HobmvsRWwOBWKYW7mzAyoKOLkozA708YtRFuD1kP
uZ7T8lDyjQTkBiOfG3cE6LNUPHlVKmJNU74MN90GTL6GRCkZhApv9PPOIcb7QU3/
r727D3xvAgMBAAECggEAIO1XGxL21OkCOeUYhE3EbSLAIczwq57pKhRHOBbd5xPW
GD3sDaoKWe12HY6Th5mGqK7UTN4XnmFhH4BJ9Zk+Kg+GPqRYUQpSl1/h2uIgzKY+
lkmM9oSS2oDL52bW1kggvCY4EC0HQEEi0YhYb6u/9AUxmtS/ELVuWWdoaC4RbVy/
dQkOaFV0/QF3qLxjhnSDlniWvFH5g256jOQGsRK7+0msaJLAbxcSP1DSFVDiEP5n
ZEZOzSDO6T4T39RNTOv7zdsw8uPXHSXhhqslYI4VIwq9ANSBrYH0Ml0DU0ei9d4l
E9bhe5xoLPswJ10S9d+Mht8g2u6BWBvAWvUFqFiosQKBgQDh4YalGf+3sTHkN5+2
GQtZwfS+VAILMaD7gvGLWaCUnmrxN/tsOeYpX2v8jY6p3CPZBge0QRC30R3HVud3
oFH4s3fKSJ+W21bMFv2jGVOJeEY37dmnvV/j4JPXsFKZdN7p2VLL1uHGNmRVl6jd
3J2pJ2g/r7GkyfE21VTjyXL9hQKBgQDfrVPS5fijDQ0LTImiJ5XqL+apXRqJVLUK
z+XTady6xzxTwnTl77e8CrYmrWySHz6dhVEBS9iau8fiYAD6ESbOiuQ7GyzMWxFd
VhcnPNttN4FJJ8Y//Y5k6rTn/t/xErNzKYD8Q7buXlJl+BVo21k8X9SWqebs+8O9
qeC2ssNKYwKBgQCBuUngq+vGjUc/8AoTRJLWO6PZYtnBoAD6MRuTkie88rYsTqBg
aWgbvqd/5bRXLQyRaPsntG5rgvd9MhXBCBvLnxZe4BJ3SwSwNUv5TWRCgQaivEDS
KtpVPvbpWmQ1qX8UAjGgy4nikf5RgcYDlN4e9XjTio2VPD0B5sbYAyu9GQKBgFzN
diTfY3yK8qmIdOZBVFLY0vPb/CGUcpTs0ucXWgxok2ARIx0vi2TKcO61L4Gk0v7a
DFTkWhdA59rFiEI4kYhKWg0n5jtXYWn/SRXviv7Sc6KdjQSJt+Wo96v1tIY6Axg5
1RlVIvXdToSeHIvnzitdez+TeItEnd74N5K1so8PAoGBAMk15qOfSrhWAkMoU9Uy
z+2H6tY5wN5Vp8j8uFXNn0bIWRWaLc6exAYO9Y20FjaDGhmEnciQb7+WiC/zTqDr
T0ZC772CXDyH8IyMABfmEg1e4LTFm4nvzBMogWIG1uCxG/sjZgkSZTyffxe7VKfk
BmaibWhJX5ZHHBa6xMozEykw
-----END PRIVATE KEY-----
"""
client_email = "voting-kds@voting-kds.iam.gserviceaccount.com"
client_id = "114425697836943875612"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/voting-kds%40voting-kds.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
